version: '2'
services:
  database:
    image: mysql:5.6
    container_name: app_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${TYPEORM_USERNAME}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}